import java.util.List;

/**
 * The CarQuizQuestion class extends the QuizQuestion class and represents a set
 * of quiz questions specific to cars.
 * It initializes the questions array with car-related questions and options.
 */
public class CarQuizQuestion extends QuizQuestion
{

	/**
	 * Constructs a new instance of CarQuizQuestion.
	 * Initializes the questions array with car-related questions and options.
	 */
	CarQuizQuestion()
	{
		super(); // Call the constructor of the superclass (QuizQuestion)
		questions = new String[][] {
				{ "What is the purpose of a catalytic converter?",
						"reduce emission", "increase torque", "filter oil",
						"increase emission" },
				{ "Which of the following is a mechanical component in a car that regulates the power generated by the engine?",
						"transmission", "clutch", "turbo", "suspension" },
				{ "What serves to engage and disengage the transmission from the engine?",
						"clutch", "thruster", "flywheel", "sparkplug" },
				{ "What is connected to the crankshaft and helps smooth out the fluctuations in engine speed?",
						"flywheel", "battery", "radiator", "steering wheel" },
				{ "What is a mechanical component used in vehicles to transmit torque and rotation from the vehicle's transmission?",
						"crankshaft", "flywheel", "spark plug",
						"filter oil" } };
	}
}